### ISSUE TITLE
panic occurs when trying to execute `revel run` on a specific case

### ISSUE THREAD

**Issue by usk83** [revel/cmd#149]
## Overview

If there is a function which takes an argument of type interface{} in controller layers, it would be panic when executing `revel run`.

## Reproduction procedure

The following is an example procedure to reproduce this problem.

1. Set up Revel tools.

```bash
go get github.com/revel/revel
go get github.com/revel/cmd/revel
```

2. Initialize skeleton application with `revel new -a XXX`
3. Add following code into app/controllers/app.go.

```go
func (c *App) Debug(data interface{}) revel.Result {
  return nil
}
```

4. Run `revel run -a XXX`

Then, a panic like below occurs.

```
Revel executing: run a Revel application
WARN  16:21:13 harness.go:170: No http.addr specified in the app.conf listening on localhost interface only. This will not allow external access to your application
panic: interface conversion: interface {} is *ast.Ident, not string

goroutine 1 [running]:
github.com/revel/cmd/logger.findInContext(0x14a1858, 0x6, 0xc4202e2dc0, 0x4, 0x4, 0xc42017e250, 0x1011b56)
  /Users/usk83/go/src/github.com/revel/cmd/logger/format.go:99 +0x13c
github.com/revel/cmd/logger.TerminalFormatHandler.func1(0xc4201c6630, 0xc4202b5150, 0x76, 0xc4202b5150)
  /Users/usk83/go/src/github.com/revel/cmd/logger/format.go:56 +0xd4
github.com/revel/log15.formatFunc.Format(0xc42013afc0, 0xc4201c6630, 0xc420280a80, 0xc4202764da, 0x3)
  /Users/usk83/go/src/github.com/revel/log15/format.go:34 +0x30
github.com/revel/log15.StreamHandler.func1(0xc4201c6630, 0x76, 0xc42017e588)
  /Users/usk83/go/src/github.com/revel/log15/handler.go:43 +0x4f
github.com/revel/log15.funcHandler.Log(0xc42016a8a0, 0xc4201c6630, 0xc4200269f8, 0xc42017e638)
  /Users/usk83/go/src/github.com/revel/log15/handler.go:31 +0x30
github.com/revel/log15.SyncHandler.func1(0xc4201c6630, 0x0, 0x0)
  /Users/usk83/go/src/github.com/revel/log15/handler.go:57 +0x91
github.com/revel/log15.funcHandler.Log(0xc42013afe0, 0xc4201c6630, 0x148e0c0, 0x1b006c8)
  /Users/usk83/go/src/github.com/revel/log15/handler.go:31 +0x30
github.com/revel/log15.LazyHandler.func1(0xc4201c6630, 0xc4202e2dc0, 0xc4202b5160)
  /Users/usk83/go/src/github.com/revel/log15/handler.go:295 +0x2ed
github.com/revel/log15.funcHandler.Log(0xc42013b000, 0xc4201c6630, 0x2, 0x2)
  /Users/usk83/go/src/github.com/revel/log15/handler.go:31 +0x30
github.com/revel/log15.CallerFileHandler.func1(0xc4201c6630, 0xc4201c6630, 0x0)
  /Users/usk83/go/src/github.com/revel/log15/handler.go:101 +0x164
github.com/revel/log15.funcHandler.Log(0xc42013b020, 0xc4201c6630, 0xc42017e7d0, 0x1145ee0)
  /Users/usk83/go/src/github.com/revel/log15/handler.go:31 +0x30
github.com/revel/cmd/logger.(*CompositeMultiHandler).Log(0xc4200ac960, 0xc4201c6630, 0x90, 0x146bc60)
  /Users/usk83/go/src/github.com/revel/cmd/logger/handlers.go:224 +0x68
github.com/revel/log15.(*swapHandler).Log(0xc420062730, 0xc4201c6630, 0x1220e32, 0xc42030e120)
  /Users/usk83/go/src/github.com/revel/log15/handler_go14.go:14 +0x77
github.com/revel/log15.(*logger).write(0xc42009ef00, 0x14ba680, 0x3d, 0x2, 0xc42030e120, 0x2, 0x2)
  /Users/usk83/go/src/github.com/revel/log15/logger.go:108 +0x237
github.com/revel/log15.(*logger).Warn(0xc42009ef00, 0x14ba680, 0x3d, 0xc42030e120, 0x2, 0x2)
  /Users/usk83/go/src/github.com/revel/log15/logger.go:154 +0x66
github.com/revel/cmd/parser.appendAction(0xc42026e840, 0xc42017ec38, 0x14fd860, 0xc420263d70, 0xc4201ed900, 0x13, 0xc420276420, 0xb, 0xc42017ec08)
  /Users/usk83/go/src/github.com/revel/cmd/parser/appends.go:137 +0x903
github.com/revel/cmd/parser.processPackage(0xc42026e840, 0xc4201ed900, 0x13, 0xc420282320, 0x42, 0xc420263dd0, 0x0)
  /Users/usk83/go/src/github.com/revel/cmd/parser/reflect.go:174 +0x97a
github.com/revel/cmd/parser.(*processContainer).processPath(0xc4201d4060, 0xc420282320, 0x42, 0x14fff60, 0xc4202040d0, 0x0, 0x0, 0xc420282320, 0x42)
  /Users/usk83/go/src/github.com/revel/cmd/parser/reflect.go:139 +0x4fd
github.com/revel/cmd/parser.(*processContainer).(github.com/revel/cmd/parser.processPath)-fm(0xc420282320, 0x42, 0x14fff60, 0xc4202040d0, 0x0, 0x0, 0x0, 0x0)
  /Users/usk83/go/src/github.com/revel/cmd/parser/reflect.go:48 +0x69
github.com/revel/cmd/utils.fsWalk.func1(0xc420282320, 0x42, 0x14fff60, 0xc4202040d0, 0x0, 0x0, 0x0, 0xc42017f2c8)
  /Users/usk83/go/src/github.com/revel/cmd/utils/file.go:237 +0x1a5
path/filepath.walk(0xc420282230, 0x42, 0x14fff60, 0xc4202040d0, 0xc4201d4090, 0x0, 0x0)
  /Users/usk83/.gvm/gos/go1.10.2/src/path/filepath/path.go:361 +0xe5
path/filepath.walk(0xc420022cc0, 0x36, 0x14fff60, 0xc4201de000, 0xc4201d4090, 0x0, 0x30)
  /Users/usk83/.gvm/gos/go1.10.2/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc420022cc0, 0x36, 0xc4201d4090, 0x0, 0xc42002e067)
  /Users/usk83/.gvm/gos/go1.10.2/src/path/filepath/path.go:403 +0x106
github.com/revel/cmd/utils.fsWalk(0xc420022cc0, 0x36, 0xc420022cc0, 0x36, 0xc4201ca020, 0x1, 0xc4201ca020)
  /Users/usk83/go/src/github.com/revel/cmd/utils/file.go:239 +0xa4
github.com/revel/cmd/utils.Walk(0xc420022cc0, 0x36, 0xc4201ca020, 0x7, 0x0)
  /Users/usk83/go/src/github.com/revel/cmd/utils/file.go:200 +0x49
github.com/revel/cmd/parser.ProcessSource(0xc42014c500, 0xc42017f8e0, 0x2, 0x2)
  /Users/usk83/go/src/github.com/revel/cmd/parser/reflect.go:48 +0x184
github.com/revel/cmd/harness.Build(0xc420152000, 0xc42014c500, 0xe, 0x0, 0x0)
  /Users/usk83/go/src/github.com/revel/cmd/harness/build.go:43 +0xc0
github.com/revel/cmd/harness.(*Harness).Refresh(0xc42008a780, 0x0)
  /Users/usk83/go/src/github.com/revel/cmd/harness/harness.go:217 +0xd4
github.com/revel/cmd/watcher.(*Watcher).notifyInProcess(0xc4200da700, 0x14f8840, 0xc42008a780, 0x0)
  /Users/usk83/go/src/github.com/revel/cmd/watcher/watcher.go:270 +0x10a
github.com/revel/cmd/watcher.(*Watcher).Notify(0xc4200da700, 0x0)
  /Users/usk83/go/src/github.com/revel/cmd/watcher/watcher.go:214 +0x3f5
github.com/revel/cmd/harness.(*Harness).Run(0xc42008a780)
  /Users/usk83/go/src/github.com/revel/cmd/harness/harness.go:269 +0x19d
main.runApp(0xc420152000, 0x17, 0x2)
  /Users/usk83/go/src/github.com/revel/cmd/revel/run.go:144 +0x7bd
main.main()
  /Users/usk83/go/src/github.com/revel/cmd/revel/revel.go:103 +0x20c
```

## Investigation

I made sure that this error happens with both 0.20.0 and 0.21.0-dev of revel.

On the previous version of revel (0.19.1), this panic does not appear. Instead, a warning like below is shown, maybe as expected.

```
WARN  16:33:02  revel reflect.go:460: Didn't understand argument 'data' of action (*App).Debug. Ignoring.
```

As far as I debugged, `findInContext` in `github.com/revel/cmd/logger/format.go` received an unexpected argument of `ctx` when an error occurred, and the value of `ctx` then was outputted as follows as `%+v` format.

```go
[]interface {}{(*ast.Ident)(0xc4202b2940), "(*App).Debug", "caller", "appends.go:137"}
```

## Supplements

Here are my environment.

OS: Mac OS X 10.11.6
Go: go1.10.2 (installed through gvm)

```bash
% echo $GOPATH
/Users/usk83/go:/Users/usk83/.gvm/pkgsets/go1.10.2/global
% echo $GOROOT
/Users/usk83/.gvm/gos/go1.10.2
% which go
/Users/usk83/.gvm/gos/go1.10.2/bin/go
% which revel
/Users/usk83/go/bin/revel
```

Although I've considered resolving this problem by myself, this seems something complicated with a parser or any other revel cores. For that reason, I've just submitted an issue.

This problem fully blocks some programs to work, it can not even start up. I hope this issue would be resolved. 

Regards,

**Comment by notzippy** [comment]
Thanks for the detailed analysis and explanation. With the latest develop branch I have not been able to repeat this error. Please reopen if this is not the case

**Comment by usk83** [comment]
OK, I'll check the latest develop branch later.

**Comment by notzippy** [comment]
Develop has merged to master, so with an update you should have the latest

**Comment by usk83** [comment]
I've tested this problem with the latest version of Revel and Confirmed it didn't occur anymore.

On the other hand, the warning message that gets displaying again looks just a bit strange, because of some format strings left behind.

This is an example warning message.

```
WARN  16:08:15 appends.go:137: Warn: Didn't understand argument '%s' of action %s. Ignoring. LOGGER_INVALID_KEY data=(*App).Debug
```

Anyway, thank you for the great updates!

**Comment by notzippy** [comment]
Ok, thanks for the update @usk83 - I have [updated the log message](https://github.com/revel/cmd/pull/161/files#diff-a580d3be99add116f7b34ba4ca1da2fdR137) and will likely push out a patch to the revel command (more to address some issues in windows that were hard to identify without a deployment) see #161
