### ISSUE TITLE
revel run nil pointer dereference

### ISSUE THREAD

**Issue by sebdah** [revel/cmd#206]
Hi,

I'm getting the following after a clean setup of a new project. I ran `revel new X`, and also `go mod vendor` to solve an issue with memcached not being found.

```
$ revel run
Revel executing: run a Revel application
Changed detected, recompiling
Parsing packages, (may require download if not cached)... Completed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x119700e]

goroutine 66 [running]:
go/ast.Walk({0x15d1d20, 0xc017748300}, {0x15da118, 0x0})
        /usr/local/Cellar/go/1.17.1/libexec/src/go/ast/walk.go:225 +0xece
go/ast.Inspect(...)
        /usr/local/Cellar/go/1.17.1/libexec/src/go/ast/walk.go:387
github.com/revel/cmd/parser2.(*SourceInfoProcessor).getValidation(0xc0000be0b0, 0xc00e15d230, 0xc0000eda40)
        /Users/sebdah/go/pkg/mod/github.com/revel/cmd@v1.0.3/parser2/source_info_processor.go:110 +0x10e
github.com/revel/cmd/parser2.(*SourceInfoProcessor).processPackage(0xc0000be0b0, 0xc0000eda40)
        /Users/sebdah/go/pkg/mod/github.com/revel/cmd@v1.0.3/parser2/source_info_processor.go:71 +0x8f5
github.com/revel/cmd/parser2.(*SourceProcessor).addSourceInfo(0xc0000ae190)
        /Users/sebdah/go/pkg/mod/github.com/revel/cmd@v1.0.3/parser2/source_processor.go:242 +0x66
github.com/revel/cmd/parser2.(*SourceProcessor).parse(0xc0000ae190)
        /Users/sebdah/go/pkg/mod/github.com/revel/cmd@v1.0.3/parser2/source_processor.go:56 +0xa8
github.com/revel/cmd/parser2.ProcessSource(0xc000065970)
        /Users/sebdah/go/pkg/mod/github.com/revel/cmd@v1.0.3/parser2/source_processor.go:32 +0x5b
github.com/revel/cmd/harness.Build(0xc000148200, 0xc00023e280)
        /Users/sebdah/go/pkg/mod/github.com/revel/cmd@v1.0.3/harness/build.go:56 +0xc7
github.com/revel/cmd/harness.(*Harness).refresh(0xc0002cc0e0)
        /Users/sebdah/go/pkg/mod/github.com/revel/cmd@v1.0.3/harness/harness.go:237 +0x105
github.com/revel/cmd/harness.(*Harness).Refresh(0xc0002cc0e0)
        /Users/sebdah/go/pkg/mod/github.com/revel/cmd@v1.0.3/harness/harness.go:210 +0x93
created by github.com/revel/cmd/harness.(*Harness).Run
        /Users/sebdah/go/pkg/mod/github.com/revel/cmd@v1.0.3/harness/harness.go:302 +0x256
```

This is with the following version:

```
$ revel version
Revel executing: displays the Revel Framework and Go version
Revel Framework :       Unknown (1.0.0 remote master branch)
Revel Cmd       :       1.0.0   (1.0.0 remote master branch)
Revel Modules   :       Unknown (1.0.0 remote master branch)


Go Location:/usr/local/bin/go

go version go1.17.1 darwin/amd64
```

Any suggestions on what I should do to resolve this?

**Comment by brendensoares** [comment]
@sebdah did you resolve it?

**Comment by sebdah** [comment]
I don't remember unfortunately 😬
